### ISSUE TITLE
The plugin doesn't work if you have multiple flutter modules

### ISSUE THREAD

**Issue by long1eu** [beansoftapp/flutter-storm-support#13]
![Screenshot 2020-09-27 at 10 47 56](https://user-images.githubusercontent.com/9283414/94359299-ed458d80-00ae-11eb-9899-8e504e6c3109.png)
![Screenshot 2020-09-27 at 10 48 22](https://user-images.githubusercontent.com/9283414/94359312-fc2c4000-00ae-11eb-93a1-b7775443164c.png)

**Comment by beansoft** [comment]
Hi, which platform are you running? Intellij IDEA Ultimate?

**Comment by long1eu** [comment]
Yes, on macos

**Comment by beansoft** [comment]
Ok, i'll working out a solution soon.

**Comment by beansoft** [comment]
Hi @long1eu I've update a new release which fixed this issue and is pending JetBrains' approval.
You can download and install it directly:

https://plugins.jetbrains.com/files/14718/98708/flutter-storm.zip?updateId=98708&pluginId=14718&family=INTELLIJ

**Comment by long1eu** [comment]
I'll have a look. Thanks for letting me know.

**Comment by beansoft** [comment]
I'll close this bug since it's fixed, if still have issue, welcome to reopen it again.
