### ISSUE TITLE
The change color feature doesn't work

### ISSUE THREAD

**Issue by long1eu** [beansoftapp/flutter-storm-support#14]
![Screenshot 2020-09-27 at 10 48 42](https://user-images.githubusercontent.com/9283414/94359321-11a16a00-00af-11eb-8025-8dce9f9d41fb.png)

**Comment by beansoft** [comment]
The build in Colors names visual edit feature not implemented yet, since there is almost 500 kinds color names defined in the Flutter source code, I've no idea how to choose them using a dialog. I'm still thing of how to do that.

I saw you had pay a subscription, so i'll fix this first.

**Comment by beansoft** [comment]
Hi @long1eu this feature is done, please take a test by download and install it locally:
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=99242

![image](https://user-images.githubusercontent.com/11939450/95650687-b42e0400-0b17-11eb-820c-769689301b4c.png)

**Comment by beansoft** [comment]
update: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=99244

**Comment by long1eu** [comment]
all works good for me. Thanks.

**Comment by beansoft** [comment]
The latest version had released and this has been fixed, so i'll close this issue.
