### ISSUE TITLE
webstorm 保持以后没有热重载

### ISSUE THREAD

**Issue by suyulin** [beansoftapp/flutter-storm-support#21]
![image](https://user-images.githubusercontent.com/6275411/119290527-3cb07d80-bc7f-11eb-8427-0c13061a0736.png)
![image](https://user-images.githubusercontent.com/6275411/119290539-46d27c00-bc7f-11eb-906a-2b60ece05d79.png)

**Comment by beansoft** [comment]
收到 我优先看一下flutter 2.0的这个问题 您用的windows 10?

**Comment by beansoft** [comment]
我试了下, 没有复现, 一定要用主工具栏上的运行按钮来跑App, 下面的那个运行按钮回头我发版去掉一下.

**Comment by suyulin** [comment]
> 收到 我优先看一下flutter 2.0的这个问题 您用的windows 10?

macos

**Comment by suyulin** [comment]
我在 Android Studio 里试一下，同一套代码，用官方的flutter 插件是可以的保存自动热重载的

**Comment by beansoft** [comment]
我打算把插件彻底升级一下和官方插件保持一致 大概需要一个月时间 因为很多代码和webstorm不兼容 有进展第一时间通知您

**Comment by suyulin** [comment]
> 我打算把插件彻底升级一下和官方插件保持一致 大概需要一个月时间 因为很多代码和webstorm不兼容 有进展第一时间通知您

这个问题和flutter 版本没有关系，本质就是向终端发送 R，r字符，请问你的测试环境是什么？

**Comment by beansoft** [comment]
我试过真机 Android 10 华为手机,  Android 模拟器, iOS 模拟器, 没有复现出来.  原理上的确是这样的, 向进程通信. WebStorm 2021.1.1

另外最近半年忙着项目, 很多代码都和官方插件脱节了, 可能会有不少bug, 因此我想最近彻底同步一次代码.

flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale
    zh-Hans)
    • Flutter version 2.0.6 at /Users/beansoft/Documents/Java/flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/beansoft/Documents/Java/android-sdk-macosx
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/beansoft/Documents/Java/android-sdk-macosx
    • Java binary at: /Applications/Android Studio
      4.2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio 4.2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 211.7233

[✓] IntelliJ IDEA Community Edition (version 2020.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.4
    • Dart plugin version 203.8173

[✓] Connected device (3 available)
    • SEA AL00 (mobile) • 2GXDU19A15005640 • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 11.2.3 20D91
      darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      90.0.4430.212

**Comment by suyulin** [comment]
![image](https://user-images.githubusercontent.com/6275411/119323374-33d89f80-bcb1-11eb-80a5-aa90df44d43c.png)
我使用了这里的命令，所以一直没有生效

**Comment by beansoft** [comment]
用主工具栏的命令 这块的回头我去掉一下 有点多余

**Comment by suyulin** [comment]
![image](https://user-images.githubusercontent.com/6275411/119324513-7ea6e700-bcb2-11eb-8951-70c14e7c10fc.png)
这个🐞，是一直存在的

**Comment by beansoft** [comment]
你加我微信 weblogic 我这周末做了一个官方同步版 刚好发你试试 github issue 沟通太慢
