### ISSUE TITLE
How do I create a flutter project in Pycharm?

### ISSUE THREAD

**Issue by Cyberavater** [beansoftapp/flutter-storm-support#22]
Well, I'm trying to open a flutter project using this plugin, how do I do that?

**Comment by beansoft** [comment]
Are you using pycharm professional or community version? To open a project, just open the project folder. To create, select File > New > Flutter project.

**Comment by beansoft** [comment]
Seems there is issues when not install Dart plugin. I've tried Pycharm CE, you must first click Plugins on welcome screen, install Dart first, then **RESTART** Pycharm, now you can click the new button again at welcome screen, there will be a new Flutter Project menu entry.

![image](https://user-images.githubusercontent.com/11939450/122112523-855cf000-ce53-11eb-9245-f901207377a5.png)
![image](https://user-images.githubusercontent.com/11939450/122112522-855cf000-ce53-11eb-8786-26f5d9344c10.png)

**Comment by beansoft** [comment]
There seems bugs with my plugin in Pycharm. I'll do a fix in 2 work days.

**Comment by Cyberavater** [comment]
Yes, I just figured it out, (Altho, there was a crash, which fixed after restarting the IDE) thanks for your feedback! But, I'd like to give 2 suggestions;
1. Prompt to install Dart if it's not already installed, (As it's installed in the default Flutter plugin in Intellij IDEA).
2. Everything in the top menu seems to be on the left side, please move them to the right side as it's expected by default to be on the top right side in the IntelliJ platform (very troublesome for working, if you have a habit of looking for them in the top right).

**Comment by Cyberavater** [comment]
I had to restore default settings to fix no. 2, and after that, it's all good.
