### ISSUE TITLE
Error creating new widget in Goland

### ISSUE THREAD

**Issue by adlandh** [beansoftapp/flutter-storm-support#26]
When creating new widget with popup menu, always get an error "Error parsing file template: Unable to find
resource 'File Header java'" and as a result the file contains only 1 line: "import 'package: flutter/material. dart';"

GoLand 2021.3
Build #GO-213.5744.269, built on December 1, 2021

**Comment by beansoft** [comment]
I've reproduced this issue, will fix it in 2 days.

**Comment by beansoft** [comment]
Fixed and wating for review  by Jetbrains.
Please have a try by downloading and install from disk first:
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=150708

**Comment by adlandh** [comment]
fixed. Thank you
