### ISSUE TITLE
FlutterStorm Show Main Toolbar does not work with new ui on Rider

### ISSUE THREAD

**Issue by okproject** [beansoftapp/flutter-storm-support#33]
### What happened
When I switch to new UI on Rider 2023.1.EAP9, Show Main Toolbar action does not take any effect on UI.

### Version information
- Rider 2023.1.EAP
- Dart 2.19.4
- FlutterStorm Plugin 2022.2.0

**Comment by beansoft** [comment]
[flutter-storm.zip](https://github.com/beansoft/flutter-storm-support/files/11079394/flutter-storm.zip)
Hi, please try this new version(still under dev to fix problems with the new 2023.1 EAP).

**Comment by beansoft** [comment]
Hi, a new version is at https://plugins.jetbrains.com/files/14718/312727/flutter-storm.zip , you may try before it's released or just wait for the approved update in plugin marketplace.

**Comment by okproject** [comment]
- I prefer to wait until it is released.
- Thank you very much for your quick response.
