### ISSUE TITLE
Tabs have no content

### ISSUE THREAD

**Issue by haringsrob** [beansoftapp/flutter-storm-support#7]
Hi, first of all, the plugin seems to work fine, it avoids me of using a separate ide.

However, the tabs Flutter inspector, Flutter performance are blank even while I started the emulator and run the app from the FL Storm panel.

Any idea of what I am missing?

**Comment by beansoft** [comment]
Can you give me some detail info about your env? I've tested the plugin myself before release.
1. Win/Mac?
2. flutter doctor output
3. what IDE and which version you are using?
4. better provide me the IDE log throught menu Help > Show log in finder.

**Comment by beansoft** [comment]
After I check your messge again, I think I know the reason.
run the app from the FL Storm panel will not display any flutter debug functions, it's just executes a simple command line, I think i'll give more detailed instructions in next release.

The right place to let these run/debug step by step/inspector to run is from the main toolbar(It is tested before release):
![image](https://user-images.githubusercontent.com/11939450/91704355-1527fb00-ebae-11ea-990f-efb8fe636ed6.png)
Here you can do run, debug with all inspectors worked.

**Comment by haringsrob** [comment]
Hi, ok that makes sense, I don't have this bar shown by default but it is ok now!

**Comment by haringsrob** [comment]
Thanks a lot for the fast reply.
